version: '1.0'

services:
  server:
    build: ../server
    ports:
      - "8080:8080"
    env_file:
      - ../server/.env
    networks:
      - projecthub

  realtime-server:
    build: ../realtime-server
    ports:
      - "4000:4000"
    env_file:
      - ../realtime-server/.env
    networks:
      - projecthub

  client:
    build: ../client
    ports:
      - "3000:4173"
    env_file:
      - ../client/.env
    depends_on:
      - server
      - realtime-server
    networks:
      - projecthub

networks:
  projecthub:
    driver: bridge