version: '1.0'

services:
  server:
    build: ../server
    ports:
      - "8080:8080"
    env_file:
      - ../server/.env
    networks:
      - projecthub
    volumes:
      - ../server/public:/app/public

  client:
    build: ../client
    ports:
      - "3000:4173"
    env_file:
      - ../client/.env
    depends_on:
      - server
    networks:
      - projecthub

networks:
  projecthub:
    driver: bridge